development:
  adapter: postgresql
  encoding: utf8
  database: wookbook_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: utf8
  database: wookbook_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: wookbook_production
  pool: 5
  username:
  password:
