development:
  adapter: postgresql
  encoding: unicode
  database: wookbook_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: wookbook_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: wookbook_production
  pool: 5
